# Generated by Django 3.0.1 on 2020-03-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.CharField(max_length=100)),
                ('tos', models.CharField(max_length=100)),
                ('fare', models.IntegerField()),
                ('classs', models.CharField(max_length=100)),
            ],
        ),
    ]
