# Generated by Django 3.0.1 on 2020-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('froms', models.CharField(max_length=100)),
                ('tos', models.CharField(max_length=100)),
                ('fare', models.IntegerField()),
                ('classs', models.CharField(max_length=100)),
            ],
        ),
    ]
